### ISSUE TITLE
create step to load input tables from CSV files

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#248]
Instead of starting with an HDF5 file containing the following inputs:
  - tazData.csv
  - accessibility.csv
  - hhFile.csv
  - personFile.csv

We'll add them to the settings file and read them in via a new model step.  The current script that does this outside of a formal activitysim run is at https://github.com/ActivitySim/activitysim/blob/shadow/scripts/mtc_inputs.py.

**Comment by blakerosenthal** [comment]
## Task Spec

[PopulationSim](https://github.com/RSGInc/populationsim) currently includes a robust model step called [input_pre_processor](https://github.com/RSGInc/populationsim/blob/master/populationsim/steps/input_pre_processor.py) that does a great job handling CSV inputs. CSVs are read from the data folder and loaded as injected tables according to the [input_table_list](https://github.com/RSGInc/populationsim/blob/c6dff05c44f602e46af5b7547e5865f20a2e7d9d/example_test/configs/settings.yaml#L32) specified in the settings config.

We will move this step to the ActivitySim package then reimport to PopulationSim.

In ActivitySim, three components will be affected:
- [settings.yaml](https://github.com/ActivitySim/activitysim/blob/master/example/configs/settings.yaml) 
  - we will add the option to specify an `input_table_list` similar to the current PopulationSim feature.
  - `input_store` can still be used to specify an HDF5 input file.
  - a `create_input_file` option will be added to build an HDF5 file from the input CSVs. This file can be used in subsequent model runs for faster load times.
- [input_pre_processor](https://github.com/ActivitySim/activitysim/tree/master/activitysim/core/steps)
  - this step will precede all other steps and inject all tables specified in settings.yaml.
  - the existing [input_store](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/input_store.py) code will be incorporated into this step and expanded to allow the user to specify exact table names and indices in HDF5 as well as CSV inputs. (This also resolves https://github.com/ActivitySim/activitysim/issues/271).
  - we will log every table name and its index and shape at load time for debugging purposes.
- [households](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/households.py), [landuse](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/landuse.py), and [persons](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/persons.py) tables will all be simplified to use the pre-injected tables instead of loading them on the fly.

Additionally:
- we will add a minimum of two unit tests for the input_pre_processor step to ensure correct behavior for both HDF5 and CSV input types.
- we will update inline code comments and RST docs to reflect these changes.
