### ISSUE TITLE
estimation data in data folder and survey_data folder

### ISSUE THREAD

**Issue by stevenhz** [ActivitySim/activitysim#485]
Hi,

I am running activitysim for estimation in order to first create EDB files using this command `activitysim run -c configs_estimation/configs -c configs -o output -d data.` 

However, the program requires to provide the persons.csv file in the data directory.  I would like to know:
- Should the `data/persons.csv`  having exact the same person_id as that in `data/survey_data/override_person.csv`? Does this also valid for households.csv?  

Thanks in advance.

**Comment by bstabler** [comment]
Yes, since the input_table_list households and persons are read first and then the survey_tables households and persons are read second and joined.  However, you could instead point the input_table_list households and persons settings to the survey_tables households and persons files to avoid having somewhat duplicative tables.

**Comment by stevenhz** [comment]
Thanks!

**Comment by bstabler** [comment]
_However, you could instead point the input_table_list households and persons settings to the survey_tables households and persons files to avoid having somewhat duplicative tables_

@mxndrwgrdnr suggested I do this in the [example_estimation](https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_estimation) to make the setup more intuitive to the user.  I think this is a good idea so I'm going to make the change.

**Comment by bstabler** [comment]
The commit above doesn't work for the existing estimation example files since the household auto_ownership variable is different in the input households table versus the override survey files.  This was likely done to illustrate/test how the auto_ownership variable can be overridden with the survey value in estimation mode.  

This is a bit complicated since the work location model is run before the auto ownership model and the work location model uses the mode choice logsum, which uses the input auto ownership value.  As a result, I can't make the change above and expect to get the same results since the mode choice logsums will be different for work location choice.  I think I need to update the expected test results to get the tests to pass.  I looked at the test data and it is several larch outputs.  @jpn-- can you take a look at this and let me know if you think we should just update the expected test results?  Thanks.

**Comment by bstabler** [comment]
We updated this and merged to develop
